### PR TITLE
Convert oembed.com to Jekyll + providers.json

### PR DESCRIPTION
**Pull request by bangpound**
I propose converting the content in this repository into a Jekyll site for Github Pages.

In this pull request, the content of the [provider implementations](http://oembed.com/#section7.1) section is [scraped](https://gist.github.com/bangpound/badaa1070bda96433182), normalized and YAML encoded. Jekyll [automatically loads](http://jekyllrb.com/docs/datafiles/) this data.

`index.htm` gets empty front matter so Jekyll will process it. The provider section content is generated from the YAML data.

A new template `providers.json.tpl` and the same providers data produces a JSON file containing all the provider data from the specification document. It has been pared down to exclude endpoint fields `docs_url`, `example_urls`, and `notes`.

Because GitHub Pages builds Jekyll sites automatically, you can see the outcome of this pull request here:

* https://bangpound.org/oembed-1
* https://bangpound.org/oembed-1/providers.json

Providers are edited in `_data/providers.yml`. Here's an example with some faked details:

```yaml
- provider_name: Flickr
  provider_url: 'http://www.flickr.com/'
  endpoints:
    - schemes:
        - 'http://*.flickr.com/photos/*'
        - 'http://flic.kr/p/*'
      url: 'http://www.flickr.com/services/oembed/'
      example_urls:
        - 'http://flickr.com/services/oembed?url=http%3A%2F%2Fflickr.com%2Fphotos%2Fbees%2F2362225867%2F'
      discovery: true
      notes:
        - 'The URL used in the example does not match any of the schemes in this description.'
      formats:
        - json
```

A provider must have a `provider_name`, a `provider_url` and one or more `endpoints`. An endpoint must have an `url`. Everything else is optional.

Fields whose name contains url (`provider_url`, `url`, `example_urls`) must always be just a URL. Schemes must be scheme strings [as described in the standard](http://oembed.com /#section2.1).

The `discovery` field indicates that an endpoint is [discoverable](http://oembed.com/#section4) as described in the standard. By default it is `false`.

The `formats` field list the format requirements of the endpoint.

The differences between the current standards document and this branch's Jekyll produced output are confined to section 7.1. They are easy to visualize by [comparing Markdown representations of the current section and the Jekyll generated section](https://gist.github.com/bangpound/8701715f0e831e53b7ac/revisions).

* Labels for endpoint fields have been normalized. URLs are always percent encoded.
* For scraped anchor links, the `href` attributes were used for URL fields. In some cases, these did not match the original 
* No more distinctive URL scheme labels for CollegeHumor, Vimeo, and others.

### CODE REVIEW

**Comment by bangpound** [comment]
I created some pull requests to edit the provider definitions, and I didn't look in the issue queue to see that @iamcal had already invited support.

This pull request begins to resolve #45 and maybe it would make it easier to close other issues, too. My work has benefitted a lot from this standard. Thank you for maintaining it. I hope I can help.

**Comment by iamcal** [comment]
does this actually work? it seems like it shouldn't since there's no reference to the yml file anywhere

i like this general approach, but since there are a bunch of things hosted under oembed.com subdirectories, it can't be moved to github-pages. i could use the yaml file to populate php pretty easily though

**Comment by iamcal** [comment]
I've taken your yaml file and used it in #88 to build the page with PHP. Thanks for taking the time to distill the list into a data file!

**Comment by bangpound** [comment]
Ha! If I had known you were using PHP here, I could have done this. Thanks for the quick turn-around!

**Pull request closed without merging**
