### PR TITLE
Add Wolfram Cloud as an OEmbed Provider

### PR DESCRIPTION
**Pull request by sumanthpikkili**
@iamcal Request to add Wolfram Cloud as an OEmbed provider

### CODE REVIEW

**Comment by iamcal** [comment]
merged and site updated, thanks. changes will be reflected when caches expire in ~1hr

**Comment by sumanthpikkili** [comment]
@iamcal Thank you so much for merging this. I still don't see the updates on https://oembed.com/. I hope I am not missing something.

**Comment by iamcal** [comment]
I see "Wolfram Cloud" on that page and also in the providers file: https://oembed.com/providers.json

**Comment by sumanthpikkili** [comment]
Thanks @iamcal. I see Wolfram Cloud listed on the site now.

**Pull request merged**
