### PR TITLE
Add 3Q to list of approved OEmbed providers 

### PR DESCRIPTION
**Pull request by ajvarinho**
@iamcal hello Cal, I've realized I made a mistake and would like to merge fixes with this PR. Thanks!

### CODE REVIEW

**Comment by iamcal** [comment]
This PR wont merge cleanly - can you take a look and amend it?

**Comment by ajvarinho** [comment]
Done, resolved the conflict.

**Comment by iamcal** [comment]
merged and site updated, thanks. changes will be reflected when caches expire in ~1hr

**Comment by ajvarinho** [comment]
Thank you very much!

**Pull request merged**
