### PR TITLE
Add providers/linkstackz.yml

### PR DESCRIPTION
**Pull request by ntsagar9**

### CODE REVIEW

**Comment by ntsagar9** [comment]
Can you please merge this PR.
@kevinansfield @jdp @emkay  @jdelStrother .

Thank you

**Comment by ntsagar9** [comment]
I am trying to set embed my site page for video post.
Can you please check and merge this.

**Comment by iamcal** [comment]
Your PR has been merged and site has been updated, thanks.

Using the central registry via HTTP is highly discouraged - you should instead use the discovery mechanism to allows services to consume OEmbed resources: https://oembed.com/#section4

If you need to consume the registry data, please use the NPM package as detailed in the README.

**Comment by ntsagar9** [comment]
I am using that as well API but it's not working on Reddit so I think let's try this way.
Thank you for merge PR.

**Pull request merged**
