### PR TITLE
Every peertube instance

### PR DESCRIPTION
**Pull request by lespacedunmatin**
[Peertube](https://joinpeertube.org/en/) is a software that you install on a web server. It allows you to create a video hosting website, so create your "homemade YouTube".

The difference to YouTube is that it’s not intended to create a huge platform centralizing videos from the whole world on a single server farm (which is horribly expensive).

On the contrary, PeerTube’s concept is to create a [network of multiple small interconnected video hosting providers](https://instances.joinpeertube.org/instances).

See the [FAQ](https://joinpeertube.org/en/faq) for more informations.

### CODE REVIEW

**Comment by lespacedunmatin** [comment]
Erf… I think it’s the `{{peertube instance URL}}/services/oembed?url={{peertube video URL on the instance}}` scheme that breaks travis… I don’t want to include by hand every 328 (and counting) instances. :-/

**Comment by tcitworld** [comment]
Maybe put the `{{ }}` parts into quotes?

**Comment by kevinansfield** [comment]
> I don’t want to include by hand every 328 (and counting) instances. :-/

Unfortunately I think that would be required for how the oembed scheme lookup works unless there is something _very_ specific in all peertube URLs such as `https://*/peertube/video/*`

It sounds like it would be more suitable for Peertube to add a meta tag to each video page as an alternative means for oembed consumers to find the oembed source. Eg, the https://framatube.org/videos/watch/217eefeb-883d-45be-b7fc-a788ad8507d3 page could have the following meta tag:

`<link rel="alternate" type="application/json+oembed" href="https://framatube.org/services/oembed?url="https://framatube.org/services/oembed?url=https%3A%2F%2Fframatube.org%2Fvideos%2Fwatch%2F217eefeb-883d-45be-b7fc-a788ad8507d3" title="My Awesome Video">`

**Comment by lespacedunmatin** [comment]
> It sounds like it would be more suitable for Peertube to add a meta tag to each video page as an alternative means for oembed consumers to find the oembed source.

It’s already in place: ``` <link rel="alternate" type="application/json+oembed" href="https://framatube.org/services/oembed?url=https%3A%2F%2Fframatube.org%2Fvideos%2Fwatch%2F217eefeb-883d-45be-b7fc-a788ad8507d3" title="What is PeerTube? (english subtitles)" /> ```

**Comment by lespacedunmatin** [comment]
> Maybe put the `{{ }}` parts into quotes?

Nope, didn’t work (at least with double quotes).

**Comment by kevinansfield** [comment]
@lespacedunmatin it won't work because it breaks the core purpose of schemes. The providers are used to generate this JSON file https://oembed.com/providers.json which is used by computers to lookup a provider given a valid URL. However, your PR is introducing schemes that can only be understood by a human.

**Comment by iamcal** [comment]
As commenters have pointed out, this does not make sense added to the providers JSON file. Discovery works fine here (the providers JSON file is not used by most consumers anyway - discovery is used instead)

**Pull request closed without merging**
