### PR TITLE
Update gong.yml

### PR DESCRIPTION
**Pull request by elikoren**
Add query parameter to scheme

### CODE REVIEW

**Comment by elikoren** [comment]
Is there any estimate on when this PR will be merged?

**Comment by iamcal** [comment]
Your PR has been merged and site has been updated, thanks.

Using the central registry is highly discouraged - you should instead use the discovery mechanism to allows services to consume OEmbed resources: https://oembed.com/#section4

**Comment by elikoren** [comment]
Thanks!
When I try to test my url (https://app.gong.io/call?id=1111111111111111111) in the "OEmbed Link Viewer" I'm getting the following error:
Oembed API Json could not be loaded: https://app.gong.io/oembed?url=https%3A%2F%2Fapp.gong.io%2Fcall%3Fid%3D1111111111111111111&format=json&maxwidth=640&maxheight=480
But when I test this request on postman, I'm getting the correct response.
Can you please assist?

**Comment by iamcal** [comment]
This repo is just for the spec and central registry - we have no control over gong.io

**Pull request merged**
