### PR TITLE
Vimeo update, add VEVO and Clipland

### PR DESCRIPTION
**Pull request by clipland**
Hi there,
this commit updates Vimeo info and adds VEVO, Clipland.

Any plans to order this file alphabetically?

### CODE REVIEW

**Comment by iamcal** [comment]
why the re-ordering of gfycat and iftt?

alphabetical ordering would be good (since appending causes merge conflicts constantly), but would need a merge linter to avoid me messing it up. i would definitely merge a patch that adds that

**Comment by clipland** [comment]
Reordering was from a hesitant attempt to introduce "popularity" sort, YT being first, then tinkering with alphabetic/alphanumeric sort - finally giving up on both.

Do you want me to append at the end or do a sort for you?

**Comment by iamcal** [comment]
i've since split the repo to use file-per-service to make this easier - can you re-submit using the new format?

**Comment by clipland** [comment]
Done. See pull request #158

**Pull request closed without merging**
