### PR TITLE
Create bitchute.yml

### PR DESCRIPTION
**Pull request by ScottCute**
Add support for Bitchute.com to oembed provider list.

### CODE REVIEW

**Comment by ScottCute** [comment]
Bump, kindly merge.

**Comment by ScottCute** [comment]
2 Weeks Bump @kevinansfield @jdp @emkay @jdelStrother

**Comment by ScottCute** [comment]
Project is dead ???

**Comment by iamcal** [comment]
Your PR has been merged and site has been updated, thanks.

Using the central registry via HTTP is highly discouraged - you should instead use the discovery mechanism to allows services to consume OEmbed resources: https://oembed.com/#section4

If you need to consume the registry data, please use the NPM package as detailed in the README.

**Pull request merged**
