### PR TITLE
Update endpoints for Sway, Spotify and YouTube

### PR DESCRIPTION
**Pull request by ndaidong**
Change logs:

- Separate Sway Office from Sway ( #621, ndaidong/oembed-parser#125 ndaidong/oembed-parser#130)
- Fix Spotify oEmbed URL (ndaidong/oembed-parser#133)
- Add YouTube Shorts endpoint (ndaidong/oembed-parser#131)

### CODE REVIEW

**Comment by iamcal** [comment]
merged and site updated, thanks. changes will be reflected when caches expire in ~1hr

**Comment by ndaidong** [comment]
@iamcal thank you, the provider list seems to be [partially updated](https://oembed.com/providers.json), but there is no [Sway Office](https://github.com/iamcal/oembed/blob/master/providers/sway_office.yaml) yet. Is it has been ignored by some filter while generating `providers.json` file?

**Comment by iamcal** [comment]
Fixed in #641 - the file had the wrong extension, but there was no test to catch that. Oops!

**Comment by ndaidong** [comment]
@iamcal thank you :+1:

**Pull request merged**
